// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovlxsjthjeiddcupkqbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92bHhzanRoamVpZGRjdXBrcWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDIxNzksImV4cCI6MjA2NDg3ODE3OX0.Cf-xSxZ98U85T5L8su5c4ORjTB4yUV8kMVkXo3pPkzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);